### ISSUE TITLE
Improvement suggestion: display model & version number of selected model 

### ISSUE THREAD

**Issue by asys3** [viadee/vPW#71]
When I create a new dashboard I have to select a model in a specific version.
After that the model is displayed.
But there's no hint on which model/version is selected.
Would be nice to have it anywhere. 
On the canvas perhaps. 
(Don't know if the top left corner labeled "BPMN" is reserved for this in feature releases.)

Best regards,
Uwe

**Comment by DaZang** [comment]
Hey Uwe,

you could actually change the Label in the corner by klicking on it and name it "MyProcess v2".
This is something that i cover in my talk at Camunda Community Summit today (which you will probably miss because of your speaker prep slot. But have a look at the recording of the session afterwards 😉 )

Do you think that will be sufficient or do we need additional labels for process and version?

Looking forward to seeing your process automation talk today at the Summit 👍

**Comment by asys3** [comment]
Hi David,
yes that works, but...it's a manual task. We don't like them, because they produce red heatmaps with overdue duration time in vpw ;-)
When I create a dashboard from scratch how vpw comes out of the box I have to select for which process I want to create the dashboard:

![grafik](https://user-images.githubusercontent.com/7109324/165884105-e96a782b-f449-45ff-8bb2-e4fae11479bd.png)

So I would suggest to simply take that process name and version number from there and set it as default process name instead of simply "BPMN". 
And yes I only had a short time to see your intro.
Could be that my suggestion was already covered by your talk.
I will look at your recording, too, for sure. Can't wait to recap the sessions!
Uwe

**Comment by DaZang** [comment]
Hey Uwe,
that's a great suggestion!

I created a new build `dev-20220429-7355a6a` for https://gallery.ecr.aws/viadee/vpw-frontend.

If you want to test it, edit your docker-compose.yml and change the image tag for frontend in line 104 like this:
``` 
vpw-frontend:
  image: 
    public.ecr.aws/viadee/vpw-frontend:dev-20220429-7355a6a
```

and run
`docker-compose down`
`docker-compose up`

Let us know if it works and how you like it! 

PS: I have a lot of catching up and recap to do on the sessions as well!

**Comment by asys3** [comment]
Awesome!
There's nothing to add. Perfect!

**Comment by asys3** [comment]
Another idea comes up in my mind seeing two versions of the same process in vpw.
After doing the analytics for both versions I could ask myself what are the changes between V1 and V2.
So a graphical diff would be nice and would help to understand the different results of the analytics.

Do you think vpw is a good place to include such a view, too (vision of vpw only pure analytics?)? 

Than it would be worth adding another ticket for it.
And of course how can it be added? another frame? overlay?

**Comment by DaZang** [comment]
A graphical diff of the model or of the numbers analysed?

By adding the two visualizations side by side you should be able to diff the numbers manually side by side. Highlighting a diff there would be overkill as all the numbers should be totally different anyway.

I think a BPMN model diff should be part of the BPMN modeling tools and not part of a process warehouse.
What do you think?
